import pandas as pd
import sqlite3
import os

# Paths
PROCESSED_PATH = "data/processed/"
FINAL_PATH = "data/final/"

# Create final folder if it doesn't exist
os.makedirs(FINAL_PATH, exist_ok=True)

# Connect to SQLite database
DB_PATH = "data/final/surf_pipeline.db"
conn = sqlite3.connect(DB_PATH)
cursor = conn.cursor()

print(f"✓ Connected to database: {DB_PATH}")


def create_dim_location():
    """Create and populate location dimension table."""

    print("Building dim_location...")

    data = [
        {
            "location_id": 1,
            "location_key": "pensacola_beach",
            "name": "Pensacola Beach",
            "state": "Florida",
            "lat": 30.3366,
            "lon": -87.1514,
            "noaa_buoy_id": "42039",
            "primary_cause": "hurricane",
            "region": "Gulf of Mexico"
        },
        {
            "location_id": 2,
            "location_key": "cocoa_beach",
            "name": "Cocoa Beach",
            "state": "Florida",
            "lat": 28.3200,
            "lon": -80.6076,
            "noaa_buoy_id": "41009",
            "primary_cause": "tropical_storm",
            "region": "Atlantic Coast"
        },
        {
            "location_id": 3,
            "location_key": "waikiki",
            "name": "Waikiki",
            "state": "Hawaii",
            "lat": 21.2769,
            "lon": -157.8286,
            "noaa_buoy_id": "51201",
            "primary_cause": "pacific_swell",
            "region": "Pacific Ocean"
        },
        {
            "location_id": 4,
            "location_key": "huntington_beach",
            "name": "Huntington Beach",
            "state": "California",
            "lat": 33.6595,
            "lon": -117.9988,
            "noaa_buoy_id": "46086",
            "primary_cause": "pacific_swell",
            "region": "Pacific Ocean"
        }
    ]

    df = pd.DataFrame(data)
    df.to_sql("dim_location", conn, if_exists="replace", index=False)
    print(f"✓ dim_location created — {len(df)} records")
    return df


def create_dim_cause():
    """Create and populate cause dimension table."""

    print("Building dim_cause...")

    data = [
        {
            "cause_id": 1,
            "cause_key": "hurricane",
            "cause_name": "Hurricane",
            "cause_category": "meteorological",
            "surfable": "Yes",
            "description": "Tropical cyclone generating large swells"
        },
        {
            "cause_id": 2,
            "cause_key": "tropical_storm",
            "cause_name": "Tropical Storm",
            "cause_category": "meteorological",
            "surfable": "Yes",
            "description": "Weaker tropical system generating moderate swells"
        },
        {
            "cause_id": 3,
            "cause_key": "pacific_swell",
            "cause_name": "Pacific Swell",
            "cause_category": "oceanographic",
            "surfable": "Yes",
            "description": "Long period swells generated by distant Pacific storms"
        },
        {
            "cause_id": 4,
            "cause_key": "seismic",
            "cause_name": "Seismic Event",
            "cause_category": "geological",
            "surfable": "No",
            "description": "Earthquake or landslide generating tsunami waves"
        },
        {
            "cause_id": 5,
            "cause_key": "swell_amplification",
            "cause_name": "Swell Amplification",
            "cause_category": "oceanographic",
            "surfable": "Yes",
            "description": "Underwater canyon or bathymetry amplifying incoming swells"
        }
    ]

    df = pd.DataFrame(data)
    df.to_sql("dim_cause", conn, if_exists="replace", index=False)
    print(f"✓ dim_cause created — {len(df)} records")
    return df

def create_dim_date():
    """Create and populate date dimension table."""

    print("Building dim_date...")

    dates = pd.date_range(start="2000-01-01", end="2023-12-31", freq="D")

    data = []
    for date in dates:
        data.append({
            "date_id": int(date.strftime("%Y%m%d")),
            "date": date.strftime("%Y-%m-%d"),
            "year": date.year,
            "month": date.month,
            "month_name": date.strftime("%B"),
            "day": date.day,
            "quarter": date.quarter,
            "season": (
                "Winter" if date.month in [12, 1, 2] else
                "Spring" if date.month in [3, 4, 5] else
                "Summer" if date.month in [6, 7, 8] else
                "Fall"
            ),
            "is_hurricane_season": "Yes" if date.month in [6, 7, 8, 9, 10, 11] else "No"
        })

    df = pd.DataFrame(data)
    df.to_sql("dim_date", conn, if_exists="replace", index=False)
    print(f"✓ dim_date created — {len(df)} records")
    return df

def create_dim_benchmark():
    """Create and populate benchmark dimension table."""

    print("Building dim_benchmark...")

    data = [
        {
            "benchmark_id": 1,
            "benchmark_key": "lituya_bay",
            "name": "Lituya Bay Megatsunami",
            "location": "Lituya Bay, Alaska",
            "year": 1958,
            "wave_height_ft": 1720,
            "wave_height_m": 524,
            "cause": "Landslide triggered by magnitude 7.8 earthquake",
            "cause_type": "seismic",
            "surfable": "No",
            "surfer": "N/A",
            "notes": "Largest wave ever recorded. Scientific upper bound only."
        },
        {
            "benchmark_id": 2,
            "benchmark_key": "nazare",
            "name": "Nazaré Big Wave Record",
            "location": "Nazaré, Portugal",
            "year": 2020,
            "wave_height_ft": 86,
            "wave_height_m": 26.2,
            "cause": "Underwater canyon amplifying Atlantic swell",
            "cause_type": "swell_amplification",
            "surfable": "Yes",
            "surfer": "Sebastian Steudtner",
            "notes": "Largest wave ever surfed. Human surfability ceiling."
        }
    ]

    df = pd.DataFrame(data)
    df.to_sql("dim_benchmark", conn, if_exists="replace", index=False)
    print(f"✓ dim_benchmark created — {len(df)} records")
    return df


def create_fact_wave_events():
    """Create and populate wave_events fact table."""

    print("Building wave_events fact table...")

    # Load cleaned buoy data
    buoy_df = pd.read_csv(f"{PROCESSED_PATH}buoy_data_clean.csv")

    # Load location dimension to get location_ids
    location_df = pd.read_sql("SELECT * FROM dim_location", conn)

    # Merge to get location_id
    buoy_df = buoy_df.merge(
        location_df[["location_key", "location_id"]],
        left_on="location",
        right_on="location_key",
        how="left"
    )

    # Build date_id
    buoy_df["date_id"] = (
        buoy_df["year"].astype(str) +
        buoy_df["month"].astype(str).str.zfill(2) +
        buoy_df["day"].astype(str).str.zfill(2)
    ).astype(int)

    # Nazare benchmark height in meters for comparison
    nazare_height_m = 26.2

    # Build fact table
    fact_df = pd.DataFrame({
        "location_id": buoy_df["location_id"],
        "date_id": buoy_df["date_id"],
        "year": buoy_df["year"],
        "month": buoy_df["month"],
        "wave_height_m": buoy_df["wave_height_m"],
        "dominant_period_sec": buoy_df["dominant_period_sec"],
        "wind_speed_ms": buoy_df["wind_speed_ms"],
        "benchmark_pct_nazare": (
            buoy_df["wave_height_m"] / nazare_height_m * 100
        ).round(2),
        "benchmark_pct_lituya": (
            buoy_df["wave_height_m"] / 524 * 100
        ).round(2),
        "source": buoy_df["source"]
    })

    fact_df.to_sql("wave_events", conn, if_exists="replace", index=False)
    print(f"✓ wave_events created — {len(fact_df)} records")
    return fact_df


if __name__ == "__main__":
    print("Building star schema...\n")

    create_dim_location()
    create_dim_cause()
    create_dim_date()
    create_dim_benchmark()
    create_fact_wave_events()

    # Verify tables created
    print("\n--- Schema Summary ---")
    tables = cursor.execute(
        "SELECT name FROM sqlite_master WHERE type='table'"
    ).fetchall()
    
    for table in tables:
        count = cursor.execute(
            f"SELECT COUNT(*) FROM {table[0]}"
        ).fetchone()[0]
        print(f"{table[0]:<20} : {count} records")

    conn.close()
    print("\n✓ Star schema complete — saved to data/final/surf_pipeline.db")